### PR TITLE
[KARAF-5108] Add Deployer feature

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/karaf-cave-pr/1/

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by jbonofre** [comment]
retest this please

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Pull request merged**
